### ISSUE TITLE
Missing key spatialdata_attrs in shapes metadata

### ISSUE THREAD

**Issue by GuoshengMa** [scverse/spatialdata#484]
I got an error when I reading the `.zarr` file provided in `Use landmark annotations to align multiple -omics layers` section.
I installed the `spatialdata` package using this code:
```bash
conda install python=3.11 --yes # python
pip install spatialdata # spatialdata
pip install "spatialdata[extra]" # visualization and IO
pip install "spatialdata[torch]" # additional dependencies
```
download the `Xenium dataset` and `Visium dataset` and rename the files to `xenium.zarr` and `visium.zarr`:
![image](https://github.com/scverse/spatialdata/assets/154969086/d503ac3e-7a83-4325-b390-d362c682b6e9)
using `sd.read_zarr()` to load the data:
```py
import numpy as np
import spatialdata as sd

xenium_sdata = sd.read_zarr("xenium.zarr")
xenium_sdata
```
and finally I got this error:
```py
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[8], [line 1](vscode-notebook-cell:?execution_count=8&line=1)
----> [1](vscode-notebook-cell:?execution_count=8&line=1) xenium_sdata = sd.read_zarr("xenium.zarr")
      [2](vscode-notebook-cell:?execution_count=8&line=2) xenium_sdata

File [c:\Users\mgssu\anaconda3\envs\spatialTranscriptome\Lib\site-packages\spatialdata\_io\io_zarr.py:123](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_zarr.py:123), in read_zarr(store, selection)
    [121](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_zarr.py:121)     f_elem = group[subgroup_name]
    [122](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_zarr.py:122)     f_elem_store = os.path.join(f_store_path, f_elem.path)
--> [123](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_zarr.py:123)     shapes[subgroup_name] = _read_shapes(f_elem_store)
    [124](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_zarr.py:124)     count += 1
    [125](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_zarr.py:125) logger.debug(f"Found {count} elements in {group}")

File [c:\Users\mgssu\anaconda3\envs\spatialTranscriptome\Lib\site-packages\spatialdata\_io\io_shapes.py:35](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_shapes.py:35), in _read_shapes(store, fmt)
     [33](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_shapes.py:33) coords = np.array(f["coords"])
     [34](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_shapes.py:34) index = np.array(f["Index"])
---> [35](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_shapes.py:35) typ = fmt.attrs_from_dict(f.attrs.asdict())
     [36](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_shapes.py:36) if typ.name == "POINT":
     [37](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/io_shapes.py:37)     radius = np.array(f["radius"])

File [c:\Users\mgssu\anaconda3\envs\spatialTranscriptome\Lib\site-packages\spatialdata\_io\format.py:108](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/format.py:108), in ShapesFormatV01.attrs_from_dict(self, metadata)
    [106](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/format.py:106) def attrs_from_dict(self, metadata: dict[str, Any]) -> GeometryType:
    [107](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/format.py:107)     if Shapes_s.ATTRS_KEY not in metadata:
--> [108](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/format.py:108)         raise KeyError(f"Missing key {Shapes_s.ATTRS_KEY} in shapes metadata.")
    [109](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/format.py:109)     metadata_ = metadata[Shapes_s.ATTRS_KEY]
    [110](file:///C:/Users/mgssu/anaconda3/envs/spatialTranscriptome/Lib/site-packages/spatialdata/_io/format.py:110)     if Shapes_s.GEOS_KEY not in metadata_:

KeyError: 'Missing key spatialdata_attrs in shapes metadata.'
```
I donot understand why this error happens, who can help me?

**Comment by LucaMarconato** [comment]
Hi, thanks for reporting. Just checking, is the issue solved now? If yes please consider sharing more insights for future users, thank you 😊

**Comment by GuoshengMa** [comment]
Hi Luca, I have solved this problem and I will share my experience below :D

In the begining, I suspect there might have some issues when I was downloading these packages because my internet connection is poor. Therefore, I re-downloaded these packages and tried to read xenium.zarr and visium.zarr files again. However, I still encountered errors, although they were different from the first ones (unfortunately, I forgot to record the error messages).

Next, I speculated that the files linked in the section `Use landmark annotations to align multiple -omics layers` might have become outdated. So, I searched for the 'visium_associated_xenium_io' folder on [sandbox](https://github.com/giovp/spatialdata-sandbox/tree/main), and followed the code therein for downloading and formatting conversion. As a result, I successfully read the visium file.

![image](https://github.com/scverse/spatialdata/assets/154969086/3cf06d43-1a1f-4866-9482-2e168c3a74d5)

**Comment by LucaMarconato** [comment]
I checked into this, using your installation and the problem is that the latest release of `spatialdata` doesn't pin down the version of Dask used, and uses the `dask-expr` backend for Dask dataframes. This means that when we use the single dispatch to check the type of the spatial element we encounter a `dask_expr._collection.DataFrame` instead of `dask.dataframe.core.DataFrame`, leading to the error that you see.

So in your case the solution is to install dask with `"dask<=2024.2.1"`.

Next week we will finally have a new release that addresses this. I will anyway release a hotfix so that if users install the library until next week the will not encounter the issue.

**Comment by GuoshengMa** [comment]
Great! I have checked my code today and found it works!

Thank you for your help!
